export const AccordionData = [
    {
        name:'ning_eaglecard',
        image:'img/home/star_eagle.png'
    },
    {
        name:'ning_elephantcard',
        image:'img/home/star_elephant.png'
    },
    {
        name:'ning_tigercard',
        image:'img/home/star_tiger.png'
    },
    {
        name:'ning_sharkcard',
        image:'img/home/star_shark.png'
    },
    {
        name:'ning_hitefoxcard',
        image:'img/home/star_hitefox.png'
    },
]